myproject/account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import home, ArticleList

app_name='account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    #path('logout/', views.LogoutView.as_view(), name='logout'),

    #path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    #path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    #path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    #path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += [
	path('', ArticleList.as_view(), name="home")
]

myproject/blog/urls.py
from django.urls import path, re_path
from .views import home, detail, index,category

app_name ="blog"
urlpatterns = [
    path('',home, name="home"),
    path('index',index, name="index"),
    path('detail/<slug:slug>',detail, name ="detail"),
    path('category/<slug:slug>', category, name ="category")
]

myproject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('account/',include('account.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/account/models.py
from django.db import models

# Create your models here.

myproject/blog/models.py
from django.utils import timezone
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Subject")
    slug = models.SlugField(max_length=100, unique=True, verbose_name ="category adress")
    status = models.BooleanField(default=True,verbose_name="status" )
    position = models.IntegerField(verbose_name= "amount")
    class Meta:
        verbose_name = "cat"
        verbose_name_plural = "categories"
        ordering =['position']
    def __str__(self): # return the name we will object calls
        return self.title

class Article(models.Model):
    STATUS_CHOICES = (
        ('d','Draft'),
        ('p',"Published"),
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique= True)
    category = models.ManyToManyField(Category, verbose_name='category', related_name="articles")
    # manay to many relation og makemigration bagefter
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="images")
    #video = models.FileField(upload_to="images")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    def __str__(self): # return the name we will object calls
        return self.title

    def category_to_str(self): # def category_to_str(self, obj): obj in admin betyder hver object men under models bruges ikke
        return ", ".join([Category.title for Category in self.category.all()])
    class Meta:
        verbose_name = "artikel_cat" #
        verbose_name_plural = "article_categories" # navn som vil stå under blog under adminside

'''
    def jpublish(self):
        return jalali_Converter(self.publish)
    jpublish.short_description ="time"
'''

myproject/account/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from blog.models import Article

# Create your views here.

@login_required
def home(request):
    return render(request, 'registration/home.html')

class ArticleList(LoginRequiredMixin, ListView): #det er vigtigt at mixin står venstre side
	queryset = Article.objects.all()
	template_name = "registration/home.html"

	def get_queryset(self):
		if self.request.user.is_superuser:
			return Article.objects.all()
		else:
			return Article.objects.filter(author=self.request.user)

myproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse #, JsonResponse
from .models import Article, Category

def index (request):
    return render(request, "blog/index.html")

def home (request):
    context = {
        "articles": Article.objects.all(), # kallder alle ellementer
        #"articles": Article.objects.filter(status="p").order_by('publish')[:1]# configure data.. det kan ordered i admin også
        "category": Category.objects.filter(status=True)
    }
    return render(request, "blog/home.html", context)

def detail(request, slug):
    context = {
        "article": Article.objects.get(slug=slug)  # den tage en object alle ellementer
    }
    return render(request, "blog/detail.html", context)
def category(request, slug):
    context = {
        "category": Category.objects.filter(status=True)# den tage en object alle ellementer
    }
    return render(request, "blog/category.html", context)



# Create your views here.
"""
def home (request):
    context = {
        "articles": Article.objects.all() # kallder alle ellementer
        #"articles": Article.objects.filter(status="p").order_by('publish')[:1]# configure data
    }
    return render(request, "blog/home.html", context)
def detail(request, slug):
    context = {
        "article": Article.objects.get(slug=slug)  # den tage en object alle ellementer
    }
    return render(request, "blog/detail.html", context)
def home (request):
    
    context = {
        "articles": [
            {
                "name":"jjjjj",
                "age":22,
                 "img": "https://static.farakav.com/files/pictures/thumb/01555538.jpg"

            },
            {
                "name": "jioiojj",
                "age": 28,
                "img": "https://static.farakav.com/files/pictures/thumb/01523029.jpg"

            }
        ]
    }

    return render(request, "blog/home.html", context)
"""

myproject/templates/blog/category.html
<center><!-- lægger den i midden -->
    {% for article in category %}
       <article>
           <a href = "{% url 'blog:category' article.slug %}">{{article.title}}</a>
           {{article.slug}}
       </article>
    {% endfor %}
</center>

myproject/templates/blog/detail.html
<<center><!-- lægger den i midden -->
       <article>
           <img src="{{article.thumbnail.url}}" alt ="{{article.title}}" width="600" height="500"><!-- storelse af billede -->
           <p>{{article.publish}}</p>
           <p>  {{article.description}}</p>
       </article>
</center>

myproject/templates/blog/home.html
<!-- Here starts the sidebar
{% for article in articles %}
   <article>
       <p> name: {{article.name}}</p>
       <p> age: {{article.age}}</p>
       <img src="{{article.img}}" alt ="{{article.age}}">
   <h1>{{article.age}}</h1>
   </article>
{% endfor %}

<h1><a href="/article/{{article.slug}}">{{article.title}}</a></h1> #hardkoding af
-->
<center><!-- lægger den i midden -->
    {% for article in articles %}
       <article>
           <h1><a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a></h1>
           <img src="{{article.thumbnail.url}}" alt ="{{article.title}}" width="600" height="500"><!-- storelse af billede -->
           <p>{{article.publish}}</p>
           <p>  {{article.description}}</p>

           {% for cat in article.category.all %}
               <a href = "#">{{cat.title}}</a>
           {% endfor %}

           </div>
       </article>
    {% endfor %}
</center>

myproject/templates/blog/index.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('/static/blog/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Man must explore, and this is exploration at its greatest
            </h2>
            <h3 class="post-subtitle">
              Problems look mighty small from 150 miles up
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on September 24, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
            </h2>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on September 18, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Science has not yet mastered prophecy
            </h2>
            <h3 class="post-subtitle">
              We predict too much for the next year and yet far too little for the next ten.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on August 24, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Failure is not an option
            </h2>
            <h3 class="post-subtitle">
              Many say exploration is part of our destiny, but it’s actually our duty to future generations.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on July 8, 2019</p>
        </div>
        <hr>
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}""></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>